const Menu = [{
        id: 1,
        image: "images/maggi.jpg",
        name: "maggi",
        category: "breakfast",
        price: "12₹",
        description: "I love Maggi realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },

    {
        id: 2,
        image: "images/pizza.jpg",
        name: "allu pakoida",
        category: "evening",
        price: "20₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 3,
        image: "images/sweet.jpg",
        name: "corn",
        category: "breakfast",
        price: "10₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 4,
        image: "../images/egg.jpg",
        name: "chola",
        category: "lunch",
        price: "50₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 5,
        image: "../images/briyani.jpg",
        name: "briyani",
        category: "evening",
        price: "80₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 6,
        image: "../images/sandwich.jpg",
        name: "sandwich",
        category: "dinner",
        price: "180₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 7,
        image: "../images/cake.jpg",
        name: "cake",
        category: "dinner",
        price: "60₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 8,
        image: "../images/briyani.jpg",
        name: "briyani",
        category: "lunch",
        price: "60₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 9,
        image: "../images/pizza.jpg",
        name: "pizza",
        category: "evening",
        price: "10₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 10,
        image: "../images/pizza.jpg",
        name: "raa",
        category: "evening",
        price: "10₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
    {
        id: 11,
        image: "../images/pizza.jpg",
        name: "avi",
        category: "evening",
        price: "10₹",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
    },
  
];
export default Menu;